# Generated by Django 5.0.7 on 2025-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_remove_subjects_session_year_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='session_year',
        ),
    ]
