# Generated by Django 5.0.7 on 2025-01-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_rename_session_year_id_students_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
    ]
