# Generated by Django 5.0.7 on 2025-01-31 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_remove_attendance_session_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
