# Generated by Django 5.0.7 on 2025-01-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_remove_attendance_session_year_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='session_year',
        ),
        migrations.AddField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
