# Generated by Django 5.0.7 on 2025-02-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_remove_attendance_session_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
