# Generated by Django 5.0.7 on 2025-02-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
