# Generated by Django 5.0.7 on 2025-02-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_delete_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel'),
        ),
    ]
